apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: postgres
  name: postgres-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - image: gcr.io/lacchain-bid/postgres:v1
        name: postgres
        ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432
        env:
        - name: POSTGRES_DB
          value: david19-db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASS
          value: David19-QweAsd  
        - name: ALLOW_IP_RANGE
          value: 0.0.0.0/0 
        - name: POSTGRES_MULTIPLE_EXTENSIONS
          value: postgis,hstore,postgis_topology,postgis_raster,pgrouting
#        volumeMounts:
#            - name: postgres-storage
#              mountPath: /data/db
#      volumes:
#        - name: postgres-storage
#          gcePersistentDisk:
#            pdName: mongo-disk
#            fsType: ext4

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres